development:
  # adapter: async
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: api_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: api_development
